### ISSUE TITLE
Error - 'No module named 'skopt''

### ISSUE THREAD

**Issue by yu3ufe** [Yodolescrypto/yodostrats#1]
I keep getting this error while backtesting the strat, any help?

**Comment by Yodolescrypto** [comment]
Hey, you probably should head over to https://github.com/freqtrade/freqtrade and reinstall completely, as I'm not sure where this is coming from. I'm using latest tags, maybe the develop branch is your solution ! (skopt should be installed along with the other modules in requirements.txt)

**Comment by yu3ufe** [comment]
The solution was to install a library called `scikit-optimize`
`pip install scikit-optimize`
and it will work, thanks anyway
