### ISSUE TITLE
binance futures leverage

### ISSUE THREAD

**Issue by mmojadad** [Yodolescrypto/yodostrats#2]
I used multiple_tf_rsi.py  with futures_market.json, 10x leverage  show on open trades but,
binance futures leverage not affected after close trades.

**Comment by Yodolescrypto** [comment]
What do you mean ? The config file is used but it goes to spot instead of futures?

**Comment by mmojadad** [comment]
@Yodolescrypto No,  The config file is used and trade done as futures but after close the trade leverage 10x  not add to my credit in binance side
