### ISSUE TITLE
CooldownPeriod

### ISSUE THREAD

**Issue by mmojadad** [Yodolescrypto/yodostrats#4]
Hi
Is server time setting important for CooldownPeriod strategy functionality ?

**Comment by pierre-az** [comment]
I'm not certain it is, as long as it doesn't vary during the CooldownPeriod (I still recommend having a correct server time for your TZ)

**Comment by Yodolescrypto** [comment]
Hi !

It isn't important for that matter, but your server time shouldn't drift during that time or you may have issues, though I believe the period is calculated on candles rather than your machine time.
I'd recommend having the right TZ set for your server.
